### ISSUE TITLE
Stopping and starting a container breaks the container instance

### ISSUE THREAD

**Issue by slovdahl** [dmart28/gcplot-docker#2] opened 2018-02-01 07:18 UTC
Whenever I try to start a stopped gcplot container instance, some of its services fail to start. This makes the instance completely unusable, I'm not able to login etc.

```
$ docker logs 351b2b5f82b8
Starting OrientDB ...
Starting OrientDB server daemon...
Waiting for the OrientDB 2424 port to be opened ...
Creating OrientDB database ...

OrientDB console v.2.2.13 (build 2.2.x@r90d7caa1e4af3fad86594e592c64dc1202558ab1; 2016-11-15 12:04:05+0000) www.orientdb.com
Type 'help' to display all the supported commands.
Installing extensions for GREMLIN language v.2.6.0

orientdb> CREATE DATABASE remote:localhost:2424/gcplot admin admin plocal


Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot create the remote storage: gcplot

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Database 'plocal:/var/lib/orientdb/gcplot' already exists
	DB name="gcplot"
	DB name="gcplot"
Creating database [remote:localhost:2424/gcplot] using the storage type [plocal]...
Starting Cassandra ...
Waiting for the Cassandra 9042  port to be opened ...
Performing CQL initialization ...
Running gcserver service ...
Starting gcserver ...
gcserver is already running ...
GCPlot instance is initialized
Registering admin user in GCPlot ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 127.0.0.1 port 9091: Connection refused
Starting nginx service ...
Starting nginx: nginx.
2018/02/01 07:08:32.147 DEBUG [c.d.d.c.Connection] Connection[localhost/127.0.0.1:9042-8, inFlight=0, closed=false] heartbeat query succeeded
2018/02/01 07:08:32.147 DEBUG [c.d.d.c.Connection] Connection[localhost/127.0.0.1:9042-4, inFlight=0, closed=false] heartbeat query succeeded
2018/02/01 07:08:32.147 DEBUG [c.d.d.c.Connection] Connection[localhost/127.0.0.1:9042-6, inFlight=0, closed=false] was inactive for 10 seconds, sending heartbeat
2018/02/01 07:08:32.148 DEBUG [c.d.d.c.Connection] Connection[localhost/127.0.0.1:9042-6, inFlight=0, closed=false] heartbeat query succeeded
2018/02/01 07:08:33.948 DEBUG [c.d.d.c.Connection] Connection[localhost/127.0.0.1:9042-2, inFlight=0, closed=false] was inactive for 10 seconds, sending heartbeat
2018/02/01 07:08:33.948 DEBUG [c.d.d.c.Connection] Connection[localhost/127.0.0.1:9042-3, inFlight=0, closed=false] was inactive for 10 seconds, sending heartbeat
2018/02/01 07:08:33.949 DEBUG [c.d.d.c.Connection] Connection[localhost/127.0.0.1:9042-3, inFlight=0, closed=false] heartbeat query succeeded
2018/02/01 07:08:33.949 DEBUG [c.d.d.c.Connection] Connection[localhost/127.0.0.1:9042-2, inFlight=0, closed=false] heartbeat query succeeded
2018/02/01 07:08:39.105 DEBUG [c.d.d.c.Connection] Connection[localhost/127.0.0.1:9042-1, inFlight=0, closed=false] was inactive for 10 seconds, sending heartbeat
2018/02/01 07:08:39.106 DEBUG [c.d.d.c.Connection] Connection[localhost/127.0.0.1:9042-1, inFlight=0, closed=false] heartbeat query succeeded
```

**Comment by dmart28** [comment] 2018-02-20 06:39
@slovdahl sorry for long delay, fixed in version 2.0.2, please check.

**Closed as completed by dmart28** 2018-02-20 06:39 UTC

**Comment by slovdahl** [comment] 2018-02-20 07:32
Thanks, seems to work!

**Comment by bobogu23** [comment] 2019-12-05 04:53
I first time to user gcplot .I use docker run -d -p 8080:80 gcplot/gcplot:2.0.2 to start gcplot,but it does not work.I can not request localhost:8080.Please help,here is the docker log below.

Starting OrientDB ...
Starting OrientDB server daemon...
Waiting for the OrientDB 2424 port to be opened ...
Creating OrientDB database ...

OrientDB console v.2.2.13 (build 2.2.x@r90d7caa1e4af3fad86594e592c64dc1202558ab1; 2016-11-15 12:04:05+0000) www.orientdb.com
Type 'help' to display all the supported commands.
Installing extensions for GREMLIN language v.2.6.0

orientdb> CREATE DATABASE remote:localhost:2424/gcplot admin admin plocal

Creating database [remote:localhost:2424/gcplot] using the storage type [plocal]...
Connecting to database [remote:localhost:2424/gcplot] with user 'admin'...OK
Database created successfully.

Current database is: remote:localhost:2424/gcplot
Starting Cassandra ...
Waiting for the Cassandra 9042  port to be opened ...
Performing CQL initialization ...

Warnings :
Materialized views are experimental and are not recommended for production use.

Running gcserver service ...
Starting gcserver ...
gcserver is not running ...
gcserver started ...
GCPlot instance is initialized
Dec 05, 2019 4:39:50 AM io.vertx.core.spi.resolver.ResolverProvider
INFO: Using the default address resolver as the dns resolver could not be loaded
Exception in thread "main" org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'analyseController': Unsatisfied dependency expressed through field 'analyseRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cassandraGCAnalyseRepository' defined in class path resource [applicationContext-cassandra.xml]: Cannot resolve reference to bean 'cassandraConnector' while setting bean property 'connector'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cassandraConnector' defined in class path resource [applicationContext-cassandra.xml]: Invocation of init method failed; nested exception is com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/127.0.0.1:9042] Cannot connect))
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at com.gcplot.bootstrap.Bootstrap.run(Bootstrap.java:68)
	at com.gcplot.bootstrap.Bootstrap.main(Bootstrap.java:32)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cassandraGCAnalyseRepository' defined in class path resource [applicationContext-cassandra.xml]: Cannot resolve reference to bean 'cassandraConnector' while setting bean property 'connector'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cassandraConnector' defined in class path resource [applicationContext-cassandra.xml]: Invocation of init method failed; nested exception is com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/127.0.0.1:9042] Cannot connect))
